In [1]:
!head book_id_map.csv

book_id_csv,book_id
0,34684622
1,34536488
2,34017076
3,71730
4,30422361
5,33503613
6,33517540
7,34467031
8,6383669

In [26]:
csv_book_mapping={}
with open('book_id_map.csv') as f:
    while True:
        line = f.readline()
        if not line:
            break
        csv_id, book_id = line.strip().split(",")
        csv_book_mapping[csv_id]=book_id

In [27]:
len(csv_book_mapping)

2360651

In [6]:
!wc -l goodreads_interactions.csv

228648343 goodreads_interactions.csv

In [9]:
!ls -lh | grep goodreads_interactions.csv

-rw-r--r-- 1 lilil lilil 4.1G Jan 13 14:04 goodreads_interactions.csv

In [12]:
!head goodreads_interactions.csv

user_id,book_id,is_read,rating,is_reviewed
0,948,1,5,0
0,947,1,5,1
0,946,1,5,0
0,945,1,5,0
0,944,1,5,0
0,943,1,5,0
0,942,1,5,0
0,941,1,5,0
0,940,1,5,0

In [39]:
liked_books = ['910444','470368', '226527','17021','5960325','11103382','1271159','3869','31296835','897906']
# liked_books = ["4408", "31147619", "29983711", "9401317", "9317691", "8153988", "20494944"]

In [40]:
overlap_users = set()

with open('goodreads_interactions.csv','r') as f:
    while True:
        line = f.readline()
        if not line:
            break
        user_id, csv_id, _, rating, _=line.split(',')
        
        if user_id in overlap_users:
            continue
        
        try:
            rating = int(rating)
        except ValueError:
            continue
            
        book_id  = csv_book_mapping[csv_id]
        
        if book_id in liked_books and rating>4:
            overlap_users.add(user_id)

In [41]:
rec_lines = []
with open('goodreads_interactions.csv','r') as f:
    while True:
        line = f.readline()
        if not line:
            break
        user_id, csv_id,_, rating, _ = line.split(',')

        if user_id in overlap_users:
            book_id = csv_book_mapping[csv_id]
            rec_lines.append([user_id, book_id, rating])

In [42]:
import pandas as pd

recs = pd.DataFrame(rec_lines, columns = ["user_id","book_id","rating"])
recs['book_id'] = recs['book_id'].astype(str)

In [43]:
top_recs = recs['book_id'].value_counts().head(10)
top_recs = top_recs.index.values

In [44]:
books_titles = pd.read_json('books_titles.json')
books_titles['book_id'] = books_titles['book_id'].astype(str)

In [45]:
books_titles.head()

,book_id,title,ratings,url,cover_image,mod_title
0,7327624,"The Unschooled Wizard (Sun Wolf and Starhawk, ...",140,https://www.goodreads.com/book/show/7327624-th...,https://images.gr-assets.com/books/1304100136m...,the unschooled wizard sun wolf and starhawk 12
1,6066819,Best Friends Forever,51184,https://www.goodreads.com/book/show/6066819-be...,https://s.gr-assets.com/assets/nophoto/book/11...,best friends forever
2,287141,The Aeneid for Boys and Girls,46,https://www.goodreads.com/book/show/287141.The...,https://s.gr-assets.com/assets/nophoto/book/11...,the aeneid for boys and girls
3,6066812,All's Fairy in Love and War (Avalon: Web of Ma...,98,https://www.goodreads.com/book/show/6066812-al...,https://images.gr-assets.com/books/1316637798m...,alls fairy in love and war avalon web of magic 8
4,287149,The Devil's Notebook,986,https://www.goodreads.com/book/show/287149.The...,https://images.gr-assets.com/books/1328768789m...,the devils notebook

In [46]:
books_titles[books_titles['book_id'].isin(top_recs)]

,book_id,title,ratings,url,cover_image,mod_title
284473,2767052,"The Hunger Games (The Hunger Games, #1)",4899965,https://www.goodreads.com/book/show/2767052-th...,https://images.gr-assets.com/books/1447303603m...,the hunger games the hunger games 1
401395,5107,The Catcher in the Rye,2086945,https://www.goodreads.com/book/show/5107.The_C...,https://images.gr-assets.com/books/1398034300m...,the catcher in the rye
446972,5907,The Hobbit,2099680,https://www.goodreads.com/book/show/5907.The_H...,https://images.gr-assets.com/books/1372847500m...,the hobbit
463463,4671,The Great Gatsby,2758812,https://www.goodreads.com/book/show/4671.The_G...,https://images.gr-assets.com/books/1490528560m...,the great gatsby
615314,5470,1984,2023937,https://www.goodreads.com/book/show/5470.1984,https://images.gr-assets.com/books/1348990566m...,1984
770177,7613,Animal Farm,1928931,https://www.goodreads.com/book/show/7613.Anima...,https://images.gr-assets.com/books/1424037542m...,animal farm
790927,2657,To Kill a Mockingbird,3255518,https://www.goodreads.com/book/show/2657.To_Ki...,https://images.gr-assets.com/books/1361975680m...,to kill a mockingbird
878545,3,Harry Potter and the Sorcerer's Stone (Harry P...,4765497,https://www.goodreads.com/book/show/3.Harry_Po...,https://images.gr-assets.com/books/1474154022m...,harry potter and the sorcerers stone harry pot...
958091,3869,A Brief History of Time,173373,https://www.goodreads.com/book/show/3869.A_Bri...,https://images.gr-assets.com/books/1333578746m...,a brief history of time
1258258,48855,The Diary of a Young Girl,2028299,https://www.goodreads.com/book/show/48855.The_...,https://images.gr-assets.com/books/1358276407m...,the diary of a young girl

In [47]:
all_recs = recs['book_id'].value_counts()

In [48]:
all_recs = all_recs.to_frame().reset_index()
all_recs.columns = ['book_id', 'book_count']

In [49]:
all_recs.head()

  book_id  book_count
0    3869        4453
1    5470        3197
2    2657        3135
3       3        2994
4    4671        2851

In [50]:
all_recs = all_recs.merge(books_titles, how="inner", on="book_id")

In [52]:
all_recs['score']=all_recs['book_count'] * (all_recs['book_count']/all_recs['ratings'])

In [53]:
all_recs.head()

,book_id,book_count,title,ratings,url,cover_image,mod_title,score
0,3869,4453,A Brief History of Time,173373,https://www.goodreads.com/book/show/3869.A_Bri...,https://images.gr-assets.com/books/1333578746m...,a brief history of time,114.373109
1,5470,3197,1984,2023937,https://www.goodreads.com/book/show/5470.1984,https://images.gr-assets.com/books/1348990566m...,1984,5.049964
2,2657,3135,To Kill a Mockingbird,3255518,https://www.goodreads.com/book/show/2657.To_Ki...,https://images.gr-assets.com/books/1361975680m...,to kill a mockingbird,3.018944
3,3,2994,Harry Potter and the Sorcerer's Stone (Harry P...,4765497,https://www.goodreads.com/book/show/3.Harry_Po...,https://images.gr-assets.com/books/1474154022m...,harry potter and the sorcerers stone harry pot...,1.881029
4,4671,2851,The Great Gatsby,2758812,https://www.goodreads.com/book/show/4671.The_G...,https://images.gr-assets.com/books/1490528560m...,the great gatsby,2.946269

In [55]:
all_recs.sort_values('score', ascending=False).head(10)

,book_id,book_count,title,ratings,url,cover_image,mod_title,score
0,3869,4453,A Brief History of Time,173373,https://www.goodreads.com/book/show/3869.A_Bri...,https://images.gr-assets.com/books/1333578746m...,a brief history of time,114.373109
7392,34927828,56,The Great Alone,70,https://www.goodreads.com/book/show/34927828-t...,https://images.gr-assets.com/books/1501852384m...,the great alone,44.800000
36,5960325,1743,Shanghai Girls (Shanghai Girls #1),108206,https://www.goodreads.com/book/show/5960325-sh...,https://images.gr-assets.com/books/1327968416m...,shanghai girls shanghai girls 1,28.076530
58,55030,1449,Cosmos,79680,https://www.goodreads.com/book/show/55030.Cosmos,https://s.gr-assets.com/assets/nophoto/book/11...,cosmos,26.350414
125,8520362,1030,The Grand Design,44203,https://www.goodreads.com/book/show/8520362-th...,https://images.gr-assets.com/books/1320558363m...,the grand design,24.000633
247,2095,742,The Universe in a Nutshell,24029,https://www.goodreads.com/book/show/2095.The_U...,https://images.gr-assets.com/books/1159814395m...,the universe in a nutshell,22.912481
135,9500416,1006,Dreams of Joy (Shanghai Girls #2),44570,https://www.goodreads.com/book/show/9500416-dr...,https://s.gr-assets.com/assets/nophoto/book/11...,dreams of joy shanghai girls 2,22.706664
16246,8514123,27,All the Talk Is Dead,35,https://www.goodreads.com/book/show/8514123-al...,https://s.gr-assets.com/assets/nophoto/book/11...,all the talk is dead,20.828571
1613,11790127,196,All the Flowers in Shanghai,1849,https://www.goodreads.com/book/show/11790127-a...,https://images.gr-assets.com/books/1316294492m...,all the flowers in shanghai,20.776636
10068,28335696,42,"Persepolis Rising (The Expanse, #7)",89,https://www.goodreads.com/book/show/28335696-p...,https://images.gr-assets.com/books/1481562381m...,persepolis rising the expanse 7,19.820225

In [56]:
popular_recs = all_recs[all_recs['book_count'] > 75].sort_values('score', ascending=False)

In [59]:
def make_clickable(val):
    return '<a target="_blank" href="{}">Goodreads</a>'.format(val)

def show_image(val):
    return '<img src="{}" width=50></img>'.format(val)

popular_recs[~popular_recs['book_id'].isin(liked_books)].head(10).style.format({'url': make_clickable, 'cover_image': show_image})