# DETE Employee Exit Survey Access Database
In this project, we'll play the role of data analyst and pretend our stakeholders want to know the following:
* Are employees who only worked for the institutes for a short period of time resigning due to some kind of dissatisfaction? What about employees who have been there longer?
* Are younger employees resigning due to some kind of dissatisfaction? What about older employees?

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dete_survey = pd.read_csv('dete-exit-survey-january-2014.csv')
tafe_survey = pd.read_csv('tafe_survey.csv')

In [3]:
display(dete_survey.head(10))

,ID,SeparationType,Cease Date,DETE Start Date,Role Start Date,Position,Classification,Region,Business Unit,Employment Status,...,Kept informed,Wellness programs,Health & Safety,Gender,Age,Aboriginal,Torres Strait,South Sea,Disability,NESB
0,1,Ill Health Retirement,08/2012,1984,2004,Public Servant,A01-A04,Central Office,Corporate Strategy and Peformance,Permanent Full-time,...,N,N,N,Male,56-60,NaN,NaN,NaN,NaN,Yes
1,2,Voluntary Early Retirement (VER),08/2012,Not Stated,Not Stated,Public Servant,AO5-AO7,Central Office,Corporate Strategy and Peformance,Permanent Full-time,...,N,N,N,Male,56-60,NaN,NaN,NaN,NaN,NaN
2,3,Voluntary Early Retirement (VER),05/2012,2011,2011,Schools Officer,NaN,Central Office,Education Queensland,Permanent Full-time,...,N,N,N,Male,61 or older,NaN,NaN,NaN,NaN,NaN
3,4,Resignation-Other reasons,05/2012,2005,2006,Teacher,Primary,Central Queensland,NaN,Permanent Full-time,...,A,N,A,Female,36-40,NaN,NaN,NaN,NaN,NaN
4,5,Age Retirement,05/2012,1970,1989,Head of Curriculum/Head of Special Education,NaN,South East,NaN,Permanent Full-time,...,N,A,M,Female,61 or older,NaN,NaN,NaN,NaN,NaN
5,6,Resignation-Other reasons,05/2012,1994,1997,Guidance Officer,NaN,Central Office,Education Queensland,Permanent Full-time,...,D,D,NaN,Female,41-45,NaN,NaN,NaN,NaN,NaN
6,7,Age Retirement,05/2012,1972,2007,Teacher,Secondary,Darling Downs South West,NaN,Permanent Part-time,...,D,D,SD,Female,56-60,NaN,NaN,NaN,NaN,NaN
7,8,Age Retirement,05/2012,1988,1990,Teacher Aide,NaN,North Coast,NaN,Permanent Part-time,...,SA,NaN,SA,Female,61 or older,NaN,NaN,NaN,NaN,NaN
8,9,Resignation-Other reasons,07/2012,2009,2009,Teacher,Secondary,North Queensland,NaN,Permanent Full-time,...,A,D,N,Female,31-35,NaN,NaN,NaN,NaN,NaN
9,10,Resignation-Other employer,2012,1997,2008,Teacher Aide,NaN,Not Stated,NaN,Permanent Part-time,...,SD,SD,SD,Female,46-50,NaN,NaN,NaN,NaN,NaN

In [4]:
dete_survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 822 entries, 0 to 821
Data columns (total 56 columns):
ID                                     822 non-null int64
SeparationType                         822 non-null object
Cease Date                             822 non-null object
DETE Start Date                        822 non-null object
Role Start Date                        822 non-null object
Position                               817 non-null object
Classification                         455 non-null object
Region                                 822 non-null object
Business Unit                          126 non-null object
Employment Status                      817 non-null object
Career move to public sector           822 non-null bool
Career move to private sector          822 non-null bool
Interpersonal conflicts                822 non-null bool
Job dissatisfaction                    822 non-null bool
Dissatisfaction with the department    822 non-null bool
Physical work environment              822 non-null bool
Lack of recognition                    822 non-null bool
Lack of job security                   822 non-null bool
Work location                          822 non-null bool
Employment conditions                  822 non-null bool
Maternity/family                       822 non-null bool
Relocation                             822 non-null bool
Study/Travel                           822 non-null bool
Ill Health                             822 non-null bool
Traumatic incident                     822 non-null bool
Work life balance                      822 non-null bool
Workload                               822 non-null bool
None of the above                      822 non-null bool
Professional Development               808 non-null object
Opportunities for promotion            735 non-null object
Staff morale                           816 non-null object
Workplace issue                        788 non-null object
Physical environment                   817 non-null object
Worklife balance                       815 non-null object
Stress and pressure support            810 non-null object
Performance of supervisor              813 non-null object
Peer support                           812 non-null object
Initiative                             813 non-null object
Skills                                 811 non-null object
Coach                                  767 non-null object
Career Aspirations                     746 non-null object
Feedback                               792 non-null object
Further PD                             768 non-null object
Communication                          814 non-null object
My say                                 812 non-null object
Information                            816 non-null object
Kept informed                          813 non-null object
Wellness programs                      766 non-null object
Health & Safety                        793 non-null object
Gender                                 798 non-null object
Age                                    811 non-null object
Aboriginal                             16 non-null object
Torres Strait                          3 non-null object
South Sea                              7 non-null object
Disability                             23 non-null object
NESB                                   32 non-null object
dtypes: bool(18), int64(1), object(37)
memory usage: 258.6+ KB

In [5]:
dete_survey.isnull()

,ID,SeparationType,Cease Date,DETE Start Date,Role Start Date,Position,Classification,Region,Business Unit,Employment Status,...,Kept informed,Wellness programs,Health & Safety,Gender,Age,Aboriginal,Torres Strait,South Sea,Disability,NESB
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,True
2,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,True,True,True,True,True
3,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
4,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,True,True,True,True,True
5,False,False,False,False,False,False,True,False,False,False,...,False,False,True,False,False,True,True,True,True,True
6,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
7,False,False,False,False,False,False,True,False,True,False,...,False,True,False,False,False,True,True,True,True,True
8,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
9,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,True,True,True,True,True
10,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,True,True,True,True,True
11,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
12,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
13,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
14,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
15,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
16,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,True,True,True,True,True
17,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
18,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,True,True,True,True,True
19,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,True,True,True,True,True
20,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
21,False,False,False,False,False,False,True,False,True,False,...,False,True,False,False,False,True,True,True,True,True
22,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,True,True,True,True,True
23,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
24,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,True,True,True,True,True
25,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,True
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
28,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,True,True,True,True,True
29,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,True,True,True,False,True
793,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
794,False,False,False,False,False,False,True,False,True,False,...,False,True,False,False,False,True,True,True,True,True
795,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
796,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
797,False,False,False,False,False,False,False,False,True,False,...,False,True,False,False,False,True,True,True,True,True
798,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,True,True,True,True,True
799,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
800,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
801,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
802,False,False,False,False,False,False,True,False,True,False,...,False,False,False,True,True,True,True,True,True,True
803,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
804,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
805,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,True,True,True,True,True
806,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,True,True,True,True,True
807,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
808,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,True,True,True,True,True
809,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
810,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
811,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,False,True
812,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
813,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
814,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,True,True,True,True,True
815,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
816,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
817,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
818,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
819,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,True
820,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,True,True,True
821,False,False,False,False,False,False,True,False,True,True,...,True,True,True,True,True,True,True,True,True,True

In [6]:
dete_survey['SeparationType'].value_counts()

Age Retirement                          285
Resignation-Other reasons               150
Resignation-Other employer               91
Resignation-Move overseas/interstate     70
Voluntary Early Retirement (VER)         67
Ill Health Retirement                    61
Other                                    49
Contract Expired                         34
Termination                              15
Name: SeparationType, dtype: int64

In [7]:
dete_survey=pd.read_csv("dete-exit-survey-january-2014.csv", na_values='Not Stated')
dete_survey_updated=dete_survey.drop(dete_survey.columns[28:49],axis=1)

From our work in the previous screen, we can first make the following observations:
* The dete_survey dataframe contains 'Not Stated' values that indicate values are missing, but they aren't represented as NaN'
* The dete_survey contains many columns that we don't need to complete our analysis.
* The dete_survey contains many of the same columns, but the column names are different.
* There are multiple columns/answers that indicate an employee resigned because they were dissatisfied.

In [8]:
dete_survey_updated.rename({'SeparationType': 'separation_type'},axis=1,inplace=True)

In [9]:
dete_survey_updated.head()

,ID,separation_type,Cease Date,DETE Start Date,Role Start Date,Position,Classification,Region,Business Unit,Employment Status,...,Work life balance,Workload,None of the above,Gender,Age,Aboriginal,Torres Strait,South Sea,Disability,NESB
0,1,Ill Health Retirement,08/2012,1984.0,2004.0,Public Servant,A01-A04,Central Office,Corporate Strategy and Peformance,Permanent Full-time,...,False,False,True,Male,56-60,NaN,NaN,NaN,NaN,Yes
1,2,Voluntary Early Retirement (VER),08/2012,NaN,NaN,Public Servant,AO5-AO7,Central Office,Corporate Strategy and Peformance,Permanent Full-time,...,False,False,False,Male,56-60,NaN,NaN,NaN,NaN,NaN
2,3,Voluntary Early Retirement (VER),05/2012,2011.0,2011.0,Schools Officer,NaN,Central Office,Education Queensland,Permanent Full-time,...,False,False,True,Male,61 or older,NaN,NaN,NaN,NaN,NaN
3,4,Resignation-Other reasons,05/2012,2005.0,2006.0,Teacher,Primary,Central Queensland,NaN,Permanent Full-time,...,False,False,False,Female,36-40,NaN,NaN,NaN,NaN,NaN
4,5,Age Retirement,05/2012,1970.0,1989.0,Head of Curriculum/Head of Special Education,NaN,South East,NaN,Permanent Full-time,...,True,False,False,Female,61 or older,NaN,NaN,NaN,NaN,NaN

In [10]:
dete_survey_updated.columns=dete_survey_updated.columns.str.strip().str.replace(' ','_').str.lower()

In [11]:
dete_survey_updated.columns

Index(['id', 'separation_type', 'cease_date', 'dete_start_date',
       'role_start_date', 'position', 'classification', 'region',
       'business_unit', 'employment_status', 'career_move_to_public_sector',
       'career_move_to_private_sector', 'interpersonal_conflicts',
       'job_dissatisfaction', 'dissatisfaction_with_the_department',
       'physical_work_environment', 'lack_of_recognition',
       'lack_of_job_security', 'work_location', 'employment_conditions',
       'maternity/family', 'relocation', 'study/travel', 'ill_health',
       'traumatic_incident', 'work_life_balance', 'workload',
       'none_of_the_above', 'gender', 'age', 'aboriginal', 'torres_strait',
       'south_sea', 'disability', 'nesb'],
      dtype='object')

In [12]:
dete_survey_updated.duplicated(['id']).value_counts()

False    822
dtype: int64

In [13]:
dete_survey_updated['separation_type'].value_counts(dropna=False)

Age Retirement                          285
Resignation-Other reasons               150
Resignation-Other employer               91
Resignation-Move overseas/interstate     70
Voluntary Early Retirement (VER)         67
Ill Health Retirement                    61
Other                                    49
Contract Expired                         34
Termination                              15
Name: separation_type, dtype: int64

Separation due to all resignation types is around 53% followed by Age Retirement at around 35%. Now we will see that resignation in tafe_survey is just less than 50 %. The high proportions of resignation types needs some answers which we will try to answer after preparing our data.

In [14]:
dete_survey_updated['separation_type'].value_counts()

Age Retirement                          285
Resignation-Other reasons               150
Resignation-Other employer               91
Resignation-Move overseas/interstate     70
Voluntary Early Retirement (VER)         67
Ill Health Retirement                    61
Other                                    49
Contract Expired                         34
Termination                              15
Name: separation_type, dtype: int64

In [15]:
dete_survey_updated['separationtype']=dete_survey_updated['separation_type'].str.split('-').str[0]
dete_resignation=dete_survey_updated.copy()[dete_survey_updated['separationtype'].str.contains(r'Resignation')]

In [16]:
display(dete_resignation)

,id,separation_type,cease_date,dete_start_date,role_start_date,position,classification,region,business_unit,employment_status,...,workload,none_of_the_above,gender,age,aboriginal,torres_strait,south_sea,disability,nesb,separationtype
3,4,Resignation-Other reasons,05/2012,2005.0,2006.0,Teacher,Primary,Central Queensland,NaN,Permanent Full-time,...,False,False,Female,36-40,NaN,NaN,NaN,NaN,NaN,Resignation
5,6,Resignation-Other reasons,05/2012,1994.0,1997.0,Guidance Officer,NaN,Central Office,Education Queensland,Permanent Full-time,...,False,False,Female,41-45,NaN,NaN,NaN,NaN,NaN,Resignation
8,9,Resignation-Other reasons,07/2012,2009.0,2009.0,Teacher,Secondary,North Queensland,NaN,Permanent Full-time,...,False,False,Female,31-35,NaN,NaN,NaN,NaN,NaN,Resignation
9,10,Resignation-Other employer,2012,1997.0,2008.0,Teacher Aide,NaN,NaN,NaN,Permanent Part-time,...,False,False,Female,46-50,NaN,NaN,NaN,NaN,NaN,Resignation
11,12,Resignation-Move overseas/interstate,2012,2009.0,2009.0,Teacher,Secondary,Far North Queensland,NaN,Permanent Full-time,...,False,False,Male,31-35,NaN,NaN,NaN,NaN,NaN,Resignation
12,13,Resignation-Other reasons,2012,1998.0,1998.0,Teacher,Primary,Far North Queensland,NaN,Permanent Full-time,...,False,False,Female,36-40,NaN,NaN,NaN,NaN,NaN,Resignation
14,15,Resignation-Other employer,2012,2007.0,2010.0,Teacher,Secondary,Central Queensland,NaN,Permanent Full-time,...,False,False,Male,31-35,NaN,NaN,NaN,NaN,NaN,Resignation
16,17,Resignation-Other reasons,2012,NaN,NaN,Teacher Aide,NaN,South East,NaN,Permanent Part-time,...,False,False,Male,61 or older,NaN,NaN,NaN,NaN,NaN,Resignation
20,21,Resignation-Other employer,2012,1982.0,1982.0,Teacher,Secondary,Central Queensland,NaN,Permanent Full-time,...,False,True,Male,56-60,NaN,NaN,NaN,NaN,NaN,Resignation
21,22,Resignation-Other reasons,2012,1980.0,2009.0,Cleaner,NaN,Darling Downs South West,NaN,Permanent Part-time,...,False,False,Female,51-55,NaN,NaN,NaN,NaN,NaN,Resignation
22,23,Resignation-Other reasons,2012,1997.0,1998.0,School Administrative Staff,NaN,Metropolitan,NaN,Permanent Part-time,...,False,False,Female,46-50,NaN,NaN,NaN,NaN,NaN,Resignation
23,24,Resignation-Other reasons,2012,1973.0,2012.0,Teacher,Primary,North Queensland,NaN,Permanent Full-time,...,False,False,Female,61 or older,NaN,NaN,NaN,NaN,NaN,Resignation
25,26,Resignation-Other reasons,2012,1995.0,2002.0,Teacher,Primary,South East,NaN,Permanent Part-time,...,False,False,Female,41-45,NaN,NaN,NaN,NaN,NaN,Resignation
27,28,Resignation-Other employer,2012,2005.0,2011.0,Public Servant,AO5-AO7,Central Office,Information and Technologies,Permanent Full-time,...,False,False,Female,21-25,Yes,NaN,NaN,NaN,NaN,Resignation
33,34,Resignation-Other reasons,2012,2003.0,2003.0,Teacher,Secondary,NaN,NaN,Permanent Full-time,...,False,False,Male,36-40,NaN,NaN,NaN,Yes,NaN,Resignation
34,35,Resignation-Other reasons,2012,2006.0,2009.0,Cleaner,NaN,Central Office,Education Queensland,Permanent Part-time,...,False,False,Male,61 or older,NaN,NaN,NaN,NaN,NaN,Resignation
37,38,Resignation-Other reasons,2012,2011.0,2011.0,Teacher Aide,NaN,Central Queensland,NaN,Temporary Part-time,...,False,True,Female,21-25,NaN,NaN,NaN,NaN,NaN,Resignation
39,40,Resignation-Move overseas/interstate,2012,NaN,NaN,Teacher,NaN,Central Queensland,NaN,Permanent Full-time,...,False,False,Female,21-25,NaN,NaN,NaN,NaN,NaN,Resignation
40,41,Resignation-Other employer,2012,1977.0,1980.0,Teacher,Primary,South East,NaN,Permanent Full-time,...,False,False,Male,56-60,NaN,NaN,NaN,NaN,NaN,Resignation
41,42,Resignation-Other reasons,2012,1974.0,1994.0,Head of Curriculum/Head of Special Education,NaN,Metropolitan,NaN,Permanent Full-time,...,False,False,Female,51-55,NaN,NaN,NaN,NaN,NaN,Resignation
42,43,Resignation-Move overseas/interstate,2012,2011.0,2011.0,Cleaner,NaN,North Coast,NaN,Permanent Part-time,...,False,True,Female,41-45,NaN,NaN,NaN,NaN,NaN,Resignation
43,44,Resignation-Other reasons,2012,1976.0,1976.0,Teacher,Primary,North Coast,NaN,Permanent Full-time,...,True,False,Male,51-55,NaN,NaN,NaN,NaN,NaN,Resignation
48,49,Resignation-Move overseas/interstate,2012,2009.0,2010.0,Cleaner,NaN,South East,NaN,Permanent Full-time,...,False,False,Male,21-25,NaN,NaN,NaN,NaN,NaN,Resignation
50,51,Resignation-Move overseas/interstate,2012,2009.0,2010.0,Cleaner,NaN,South East,NaN,Permanent Full-time,...,False,False,Male,21-25,NaN,NaN,NaN,NaN,NaN,Resignation
51,52,Resignation-Other reasons,2012,1993.0,1993.0,Cleaner,NaN,South East,NaN,Permanent Full-time,...,False,True,Female,61 or older,NaN,NaN,NaN,NaN,NaN,Resignation
55,56,Resignation-Other employer,2012,2008.0,2008.0,Teacher Aide,NaN,Metropolitan,NaN,Permanent Part-time,...,False,True,Female,26-30,NaN,NaN,NaN,NaN,NaN,Resignation
57,58,Resignation-Other employer,2012,2003.0,2012.0,Teacher,Secondary,Darling Downs South West,NaN,Permanent Full-time,...,False,False,Male,46-50,NaN,NaN,NaN,NaN,NaN,Resignation
61,62,Resignation-Other reasons,2012,2011.0,2011.0,Schools Officer,NaN,Central Queensland,NaN,Temporary Part-time,...,False,False,Female,31-35,NaN,NaN,NaN,NaN,NaN,Resignation
69,70,Resignation-Other reasons,2012,2006.0,NaN,Public Servant,AO5-AO7,Central Office,Information and Technologies,Permanent Full-time,...,False,False,Female,36-40,NaN,NaN,NaN,NaN,NaN,Resignation
71,72,Resignation-Other reasons,2012,2011.0,2011.0,Teacher Aide,NaN,Far North Queensland,NaN,Permanent Part-time,...,False,False,Female,36-40,NaN,NaN,NaN,NaN,NaN,Resignation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,749,Resignation-Move overseas/interstate,01/2014,2008.0,2008.0,Teacher,Primary,North Coast,NaN,Permanent Full-time,...,False,False,Female,41-45,NaN,NaN,NaN,NaN,NaN,Resignation
751,753,Resignation-Other reasons,12/2013,2005.0,2005.0,Cleaner,NaN,Central Office,Education Queensland,Permanent Part-time,...,False,False,Male,61 or older,NaN,NaN,NaN,NaN,NaN,Resignation
752,754,Resignation-Other reasons,11/2013,1998.0,NaN,Teacher Aide,NaN,Darling Downs South West,NaN,Permanent Part-time,...,False,False,Female,46-50,NaN,NaN,NaN,Yes,NaN,Resignation
753,755,Resignation-Other employer,11/2013,2004.0,2011.0,Teacher,Primary,Central Queensland,NaN,Permanent Full-time,...,False,False,Female,31-35,NaN,NaN,NaN,NaN,NaN,Resignation
755,757,Resignation-Other employer,12/2013,2012.0,2013.0,Teacher,Primary,Central Queensland,NaN,Permanent Part-time,...,False,True,Female,41-45,NaN,NaN,NaN,NaN,NaN,Resignation
762,764,Resignation-Other employer,07/2006,2006.0,2006.0,Teacher,Primary,Metropolitan,NaN,Permanent Part-time,...,False,False,Female,41-45,NaN,NaN,NaN,NaN,NaN,Resignation
766,768,Resignation-Other employer,01/2014,2007.0,2007.0,Teacher,Primary,Metropolitan,NaN,Permanent Full-time,...,False,False,Male,26-30,NaN,NaN,NaN,NaN,NaN,Resignation
769,771,Resignation-Other reasons,11/2013,2008.0,NaN,Teacher Aide,NaN,South East,NaN,Permanent Full-time,...,False,False,Female,46-50,NaN,NaN,NaN,NaN,NaN,Resignation
770,772,Resignation-Other reasons,NaN,1987.0,1987.0,Cleaner,NaN,Darling Downs South West,NaN,Permanent Part-time,...,False,True,Female,61 or older,NaN,NaN,NaN,NaN,NaN,Resignation
771,773,Resignation-Other employer,01/2014,2002.0,2007.0,Head of Curriculum/Head of Special Education,NaN,Central Queensland,NaN,Permanent Full-time,...,False,False,Male,36-40,NaN,NaN,NaN,NaN,NaN,Resignation
774,776,Resignation-Other employer,NaN,2005.0,2005.0,Teacher Aide,NaN,Central Queensland,NaN,Permanent Part-time,...,False,True,Female,41-45,NaN,NaN,NaN,NaN,NaN,Resignation
784,786,Resignation-Other reasons,10/2013,2013.0,2013.0,Teacher,Secondary,Central Queensland,NaN,Permanent Full-time,...,False,False,Female,21-25,NaN,NaN,NaN,NaN,NaN,Resignation
786,788,Resignation-Other employer,01/2014,1994.0,2008.0,Teacher,Secondary,Darling Downs South West,NaN,Permanent Full-time,...,False,False,Female,41-45,NaN,NaN,NaN,NaN,NaN,Resignation
788,790,Resignation-Other employer,NaN,1990.0,2010.0,Teacher,Secondary,Metropolitan,NaN,Permanent Full-time,...,False,False,Female,41-45,NaN,NaN,NaN,NaN,NaN,Resignation
789,791,Resignation-Other reasons,01/2014,1983.0,1999.0,"School Based Professional Staff (Therapist, nu...",NaN,Metropolitan,NaN,Permanent Part-time,...,False,True,Female,51-55,NaN,NaN,NaN,NaN,NaN,Resignation
790,792,Resignation-Other reasons,01/2014,2008.0,2008.0,Teacher,Secondary,North Coast,NaN,Permanent Full-time,...,True,False,Male,36-40,NaN,NaN,NaN,NaN,NaN,Resignation
791,793,Resignation-Other reasons,NaN,2007.0,2007.0,Public Servant,A01-A04,Metropolitan,NaN,Permanent Part-time,...,False,False,Female,46-50,NaN,NaN,NaN,NaN,NaN,Resignation
794,796,Resignation-Move overseas/interstate,11/2013,NaN,NaN,Cleaner,NaN,NaN,NaN,Permanent Part-time,...,False,False,Female,36-40,NaN,NaN,NaN,NaN,NaN,Resignation
797,799,Resignation-Move overseas/interstate,NaN,2000.0,2013.0,Public Servant,A01-A04,South East,NaN,Permanent Part-time,...,False,False,Female,36-40,NaN,NaN,NaN,NaN,NaN,Resignation
798,800,Resignation-Move overseas/interstate,NaN,1995.0,NaN,Teacher Aide,NaN,Darling Downs South West,NaN,Permanent Part-time,...,False,False,Female,36-40,NaN,NaN,NaN,NaN,NaN,Resignation
802,804,Resignation-Move overseas/interstate,12/2013,NaN,NaN,Teacher Aide,NaN,Metropolitan,NaN,Permanent Part-time,...,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Resignation
803,805,Resignation-Other employer,01/2014,2004.0,2007.0,Teacher,Primary,Darling Downs South West,NaN,Permanent Full-time,...,False,False,Female,46-50,NaN,NaN,NaN,NaN,NaN,Resignation
804,806,Resignation-Other employer,01/2014,2008.0,2013.0,Teacher,Primary,Darling Downs South West,NaN,Permanent Part-time,...,False,False,Female,26-30,NaN,NaN,NaN,NaN,NaN,Resignation
806,808,Resignation-Other employer,12/2013,2005.0,2005.0,Cleaner,NaN,Central Queensland,NaN,Permanent Part-time,...,False,False,Female,41-45,NaN,NaN,NaN,NaN,NaN,Resignation
807,809,Resignation-Other reasons,12/2013,2004.0,2004.0,Teacher,Primary,Central Queensland,NaN,Permanent Full-time,...,False,False,Female,36-40,NaN,NaN,NaN,NaN,NaN,Resignation
808,810,Resignation-Other reasons,12/2013,2010.0,2010.0,Teacher Aide,NaN,NaN,NaN,Permanent Part-time,...,False,False,Female,26-30,NaN,NaN,NaN,NaN,NaN,Resignation
815,817,Resignation-Other employer,01/2014,2012.0,2012.0,Teacher,Primary,Far North Queensland,NaN,Permanent Full-time,...,False,False,Male,21-25,NaN,NaN,NaN,NaN,NaN,Resignation
816,818,Resignation-Move overseas/interstate,01/2014,2012.0,2012.0,Teacher,Secondary,North Coast,NaN,Permanent Full-time,...,False,False,Female,21-25,NaN,NaN,NaN,NaN,NaN,Resignation
819,821,Resignation-Move overseas/interstate,01/2014,2009.0,2009.0,Public Servant,A01-A04,Central Office,Education Queensland,Permanent Full-time,...,False,False,Female,31-35,NaN,NaN,NaN,NaN,NaN,Resignation
821,823,Resignation-Move overseas/interstate,12/2013,NaN,NaN,Teacher Aide,NaN,Metropolitan,NaN,NaN,...,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Resignation

## Note that dete_survey_updated dataframe contains multiple separation types with the string 'Resignation':
* Resignation-Other reasons
* Resignation-Other employer
* Resignation-Move overseas/interstate

## Data Verification / Checking Validity
Now we will check the validity of dates and years in our dataset. Starting with `cease_date`:, the last year of a person's employment should not be more than the current year(the year the data was created). Similarly,for `date_start_date` , we can say that people working here wont be over 60, and reasoning that they started working their in their 20's, we can say that the least value for this column can be around 1940.

In [17]:
dete_survey_updated['cease_date'].value_counts()

2012       344
2013       200
01/2014     43
12/2013     40
09/2013     34
06/2013     27
07/2013     22
10/2013     20
11/2013     16
08/2013     12
05/2013      7
05/2012      6
04/2014      2
04/2013      2
07/2014      2
02/2014      2
08/2012      2
2010         1
2014         1
07/2006      1
07/2012      1
09/2014      1
09/2010      1
11/2012      1
Name: cease_date, dtype: int64

In [18]:
dete_resignation['cease_date']=dete_resignation['cease_date'].str.extract(r'(?P<Years>[1-2][0-9]{3})')
dete_resignation['cease_date']=dete_resignation['cease_date'].astype(float)
dete_resignation['cease_date'].value_counts()

2013.0    146
2012.0    129
2014.0     22
2010.0      2
2006.0      1
Name: cease_date, dtype: int64

In [19]:
dete_resignation['dete_start_date']=dete_resignation['dete_start_date'].astype(float)
dete_resignation['dete_start_date'].value_counts().sort_index(ascending=True)

1963.0     1
1971.0     1
1972.0     1
1973.0     1
1974.0     2
1975.0     1
1976.0     2
1977.0     1
1980.0     5
1982.0     1
1983.0     2
1984.0     1
1985.0     3
1986.0     3
1987.0     1
1988.0     4
1989.0     4
1990.0     5
1991.0     4
1992.0     6
1993.0     5
1994.0     6
1995.0     4
1996.0     6
1997.0     5
1998.0     6
1999.0     8
2000.0     9
2001.0     3
2002.0     6
2003.0     6
2004.0    14
2005.0    15
2006.0    13
2007.0    21
2008.0    22
2009.0    13
2010.0    17
2011.0    24
2012.0    21
2013.0    10
Name: dete_start_date, dtype: int64

In [20]:
dete_resignation['institute_service'] = (dete_resignation['cease_date'] - dete_resignation['dete_start_date'])
dete_resignation['institute_service'].value_counts()

5.0     23
1.0     22
3.0     20
0.0     20
6.0     17
4.0     16
9.0     14
2.0     14
7.0     13
13.0     8
8.0      8
20.0     7
15.0     7
10.0     6
22.0     6
14.0     6
17.0     6
12.0     6
16.0     5
18.0     5
23.0     4
11.0     4
24.0     4
39.0     3
19.0     3
21.0     3
32.0     3
28.0     2
26.0     2
25.0     2
30.0     2
36.0     2
29.0     1
33.0     1
42.0     1
27.0     1
41.0     1
35.0     1
38.0     1
34.0     1
49.0     1
31.0     1
Name: institute_service, dtype: int64

* Excluding the null values of the institute_service field from the DETE dataset, we observe that 42% of the employees worked at most 5 years.

In [21]:
dete_resignation['institute_service'].isnull().sum()

38

In [23]:
dete_resignation.loc[:,'job_dissatisfaction':'workload']

,job_dissatisfaction,dissatisfaction_with_the_department,physical_work_environment,lack_of_recognition,lack_of_job_security,work_location,employment_conditions,maternity/family,relocation,study/travel,ill_health,traumatic_incident,work_life_balance,workload
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,True,True,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,True,True,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,True,True,False,False,False,False,False
12,False,False,False,False,False,False,False,True,False,False,False,False,False,False
14,True,True,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,True,False,False,False,False,True,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,True,False,True,False,False,False,False,False,False,False,False,True,False
23,True,False,False,False,False,True,False,True,False,False,False,False,True,False
25,False,False,False,False,False,False,False,False,False,False,False,False,True,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,True,False,False,False,False,False,False,False,True,False,False
34,False,False,False,False,False,False,False,False,False,False,False,False,True,False
37,False,False,False,False,False,False,False,False,False,False,False,False,False,False
39,True,False,False,True,False,False,True,False,False,False,False,False,True,False
40,False,False,False,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,False,True,False
42,False,False,False,False,False,False,False,False,False,False,False,False,False,False
43,True,False,False,False,False,False,False,False,False,False,False,False,True,True
48,False,False,False,False,False,False,False,False,True,False,False,False,False,False
50,False,False,False,False,False,False,False,False,True,False,False,False,False,False
51,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55,False,False,False,False,False,False,False,False,False,False,False,False,False,False
57,False,False,False,False,False,False,False,False,False,False,False,False,False,False
61,False,False,False,False,False,False,False,False,True,False,False,False,False,False
69,True,False,False,False,False,True,False,False,False,False,False,False,False,False
71,False,False,False,False,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,False,False,False,False,False,False,False,True,True,False,False,False,False,False
751,True,False,False,False,False,False,False,False,False,False,False,False,False,False
752,False,False,False,False,False,False,False,False,False,False,True,True,False,False
753,True,False,False,False,False,False,False,False,False,False,True,False,True,False
755,False,False,False,False,False,False,False,False,False,False,False,False,False,False
762,False,False,False,False,False,False,False,False,False,False,False,False,False,False
766,False,False,False,False,False,False,False,False,False,False,False,False,False,False
769,False,False,False,False,False,False,False,False,False,False,True,False,False,False
770,False,False,False,False,False,False,False,False,False,False,False,False,False,False
771,False,False,False,False,False,False,False,False,False,False,False,False,False,False
774,False,False,False,False,False,False,False,False,False,False,False,False,False,False
784,True,False,False,True,False,False,False,False,False,False,False,False,True,False
786,True,False,False,False,True,False,False,False,False,False,False,False,False,False
788,False,False,False,False,False,False,False,False,False,False,False,False,False,False
789,False,False,False,False,False,False,False,False,False,False,False,False,False,False
790,False,False,False,True,False,False,True,False,False,False,False,False,False,True
791,False,False,False,True,False,False,False,False,False,False,False,False,False,False
794,False,False,False,False,False,False,False,False,True,False,False,False,False,False
797,False,False,False,False,False,False,False,True,True,False,False,False,False,False
798,False,False,False,False,False,False,False,False,False,False,False,False,False,False
802,False,False,False,False,False,False,False,False,True,False,False,False,False,False
803,False,False,False,False,False,False,False,False,False,False,False,False,False,False
804,False,False,False,False,False,False,False,False,False,False,False,False,False,False
806,False,False,False,False,False,False,False,False,True,False,False,False,False,False
807,False,True,False,False,False,False,False,False,False,False,False,False,True,False
808,False,False,False,False,False,False,False,True,False,False,False,False,False,False
815,False,False,False,False,False,False,False,False,False,False,False,False,False,False
816,False,False,False,False,False,False,False,False,False,True,False,False,False,False
819,False,False,False,False,False,False,False,True,True,False,False,False,True,False
821,False,False,False,False,False,False,False,False,False,False,False,False,False,False

So since these columns have boolean input values, even if one of the column to a corresponding row states false, then that employee will be classified as 'dissatisfied'. Before proceeding, I think we should not include columns such from maternity/family to traumatic_incident in columns such as dissatisfied as they are not related to the institute.

In [25]:
# we will create a column 'dissatisfied' which will be of Boolean type
# the role of 'any' is to return whether any element is True
def update_vals(x):
    if x=='-':
        return False
    elif pd.isnull(x):
        return np.nan
    else:
        return True
dete_resignation['dissatisfied']=dete_resignation[['job_dissatisfaction',
                                                  'dissatisfaction_with_the_department',
                                                  'physical_work_environment','lack_of_recognition',
                                                  'lack_of_job_security','work_location','employment_conditions',
                                                  'work_life_balance','workload']].any(1,skipna=False)
dete_resignation_up=dete_resignation.copy()
dete_resignation_up['dissatisfied'].value_counts(dropna=False)

False    162
True     149
Name: dissatisfied, dtype: int64

In [28]:
dete_resignation_up['dissatisfied'].head(10)

3     False
5      True
8     False
9      True
11    False
12    False
14     True
16     True
20    False
21    False
Name: dissatisfied, dtype: bool

In [30]:
tafe_survey.head()

,Record ID,Institute,WorkArea,CESSATION YEAR,Reason for ceasing employment,Contributing Factors. Career Move - Public Sector,Contributing Factors. Career Move - Private Sector,Contributing Factors. Career Move - Self-employment,Contributing Factors. Ill Health,Contributing Factors. Maternity/Family,...,Workplace. Topic:Does your workplace promote a work culture free from all forms of unlawful discrimination?,Workplace. Topic:Does your workplace promote and practice the principles of employment equity?,Workplace. Topic:Does your workplace value the diversity of its employees?,Workplace. Topic:Would you recommend the Institute as an employer to others?,Gender. What is your Gender?,CurrentAge. Current Age,Employment Type. Employment Type,Classification. Classification,LengthofServiceOverall. Overall Length of Service at Institute (in years),LengthofServiceCurrent. Length of Service at current workplace (in years)
0,6.341330e+17,Southern Queensland Institute of TAFE,Non-Delivery (corporate),2010.0,Contract Expired,NaN,NaN,NaN,NaN,NaN,...,Yes,Yes,Yes,Yes,Female,26 30,Temporary Full-time,Administration (AO),1-2,1-2
1,6.341337e+17,Mount Isa Institute of TAFE,Non-Delivery (corporate),2010.0,Retirement,-,-,-,-,-,...,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN
2,6.341388e+17,Mount Isa Institute of TAFE,Delivery (teaching),2010.0,Retirement,-,-,-,-,-,...,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN
3,6.341399e+17,Mount Isa Institute of TAFE,Non-Delivery (corporate),2010.0,Resignation,-,-,-,-,-,...,Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN
4,6.341466e+17,Southern Queensland Institute of TAFE,Delivery (teaching),2010.0,Resignation,-,Career Move - Private Sector,-,-,-,...,Yes,Yes,Yes,Yes,Male,41 45,Permanent Full-time,Teacher (including LVT),3-4,3-4

In [31]:
tafe_survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 72 columns):
Record ID                                                                                                                                                        702 non-null float64
Institute                                                                                                                                                        702 non-null object
WorkArea                                                                                                                                                         702 non-null object
CESSATION YEAR                                                                                                                                                   695 non-null float64
Reason for ceasing employment                                                                                                                                    701 non-null object
Contributing Factors. Career Move - Public Sector                                                                                                                437 non-null object
Contributing Factors. Career Move - Private Sector                                                                                                               437 non-null object
Contributing Factors. Career Move - Self-employment                                                                                                              437 non-null object
Contributing Factors. Ill Health                                                                                                                                 437 non-null object
Contributing Factors. Maternity/Family                                                                                                                           437 non-null object
Contributing Factors. Dissatisfaction                                                                                                                            437 non-null object
Contributing Factors. Job Dissatisfaction                                                                                                                        437 non-null object
Contributing Factors. Interpersonal Conflict                                                                                                                     437 non-null object
Contributing Factors. Study                                                                                                                                      437 non-null object
Contributing Factors. Travel                                                                                                                                     437 non-null object
Contributing Factors. Other                                                                                                                                      437 non-null object
Contributing Factors. NONE                                                                                                                                       437 non-null object
Main Factor. Which of these was the main factor for leaving?                                                                                                     113 non-null object
InstituteViews. Topic:1. I feel the senior leadership had a clear vision and direction                                                                           608 non-null object
InstituteViews. Topic:2. I was given access to skills training to help me do my job better                                                                       613 non-null object
InstituteViews. Topic:3. I was given adequate opportunities for personal development                                                                             610 non-null object
InstituteViews. Topic:4. I was given adequate opportunities for promotion within %Institute]Q25LBL%                                                              608 non-null object
InstituteViews. Topic:5. I felt the salary for the job was right for the responsibilities I had                                                                  615 non-null object
InstituteViews. Topic:6. The organisation recognised when staff did good work                                                                                    607 non-null object
InstituteViews. Topic:7. Management was generally supportive of me                                                                                               614 non-null object
InstituteViews. Topic:8. Management was generally supportive of my team                                                                                          608 non-null object
InstituteViews. Topic:9. I was kept informed of the changes in the organisation which would affect me                                                            610 non-null object
InstituteViews. Topic:10. Staff morale was positive within the Institute                                                                                         602 non-null object
InstituteViews. Topic:11. If I had a workplace issue it was dealt with quickly                                                                                   601 non-null object
InstituteViews. Topic:12. If I had a workplace issue it was dealt with efficiently                                                                               597 non-null object
InstituteViews. Topic:13. If I had a workplace issue it was dealt with discreetly                                                                                601 non-null object
WorkUnitViews. Topic:14. I was satisfied with the quality of the management and supervision within my work unit                                                  609 non-null object
WorkUnitViews. Topic:15. I worked well with my colleagues                                                                                                        605 non-null object
WorkUnitViews. Topic:16. My job was challenging and interesting                                                                                                  607 non-null object
WorkUnitViews. Topic:17. I was encouraged to use my initiative in the course of my work                                                                          610 non-null object
WorkUnitViews. Topic:18. I had sufficient contact with other people in my job                                                                                    613 non-null object
WorkUnitViews. Topic:19. I was given adequate support and co-operation by my peers to enable me to do my job                                                     609 non-null object
WorkUnitViews. Topic:20. I was able to use the full range of my skills in my job                                                                                 609 non-null object
WorkUnitViews. Topic:21. I was able to use the full range of my abilities in my job. ; Category:Level of Agreement; Question:YOUR VIEWS ABOUT YOUR WORK UNIT]    608 non-null object
WorkUnitViews. Topic:22. I was able to use the full range of my knowledge in my job                                                                              608 non-null object
WorkUnitViews. Topic:23. My job provided sufficient variety                                                                                                      611 non-null object
WorkUnitViews. Topic:24. I was able to cope with the level of stress and pressure in my job                                                                      610 non-null object
WorkUnitViews. Topic:25. My job allowed me to balance the demands of work and family to my satisfaction                                                          611 non-null object
WorkUnitViews. Topic:26. My supervisor gave me adequate personal recognition and feedback on my performance                                                      606 non-null object
WorkUnitViews. Topic:27. My working environment was satisfactory e.g. sufficient space, good lighting, suitable seating and working area                         610 non-null object
WorkUnitViews. Topic:28. I was given the opportunity to mentor and coach others in order for me to pass on my skills and knowledge prior to my cessation date    609 non-null object
WorkUnitViews. Topic:29. There was adequate communication between staff in my unit                                                                               603 non-null object
WorkUnitViews. Topic:30. Staff morale was positive within my work unit                                                                                           606 non-null object
Induction. Did you undertake Workplace Induction?                                                                                                                619 non-null object
InductionInfo. Topic:Did you undertake a Corporate Induction?                                                                                                    432 non-null object
InductionInfo. Topic:Did you undertake a Institute Induction?                                                                                                    483 non-null object
InductionInfo. Topic: Did you undertake Team Induction?                                                                                                          440 non-null object
InductionInfo. Face to Face Topic:Did you undertake a Corporate Induction; Category:How it was conducted?                                                        555 non-null object
InductionInfo. On-line Topic:Did you undertake a Corporate Induction; Category:How it was conducted?                                                             555 non-null object
InductionInfo. Induction Manual Topic:Did you undertake a Corporate Induction?                                                                                   555 non-null object
InductionInfo. Face to Face Topic:Did you undertake a Institute Induction?                                                                                       530 non-null object
InductionInfo. On-line Topic:Did you undertake a Institute Induction?                                                                                            555 non-null object
InductionInfo. Induction Manual Topic:Did you undertake a Institute Induction?                                                                                   553 non-null object
InductionInfo. Face to Face Topic: Did you undertake Team Induction; Category?                                                                                   555 non-null object
InductionInfo. On-line Topic: Did you undertake Team Induction?process you undertook and how it was conducted.]                                                  555 non-null object
InductionInfo. Induction Manual Topic: Did you undertake Team Induction?                                                                                         555 non-null object
Workplace. Topic:Did you and your Manager develop a Performance and Professional Development Plan (PPDP)?                                                        608 non-null object
Workplace. Topic:Does your workplace promote a work culture free from all forms of unlawful discrimination?                                                      594 non-null object
Workplace. Topic:Does your workplace promote and practice the principles of employment equity?                                                                   587 non-null object
Workplace. Topic:Does your workplace value the diversity of its employees?                                                                                       586 non-null object
Workplace. Topic:Would you recommend the Institute as an employer to others?                                                                                     581 non-null object
Gender. What is your Gender?                                                                                                                                     596 non-null object
CurrentAge. Current Age                                                                                                                                          596 non-null object
Employment Type. Employment Type                                                                                                                                 596 non-null object
Classification. Classification                                                                                                                                   596 non-null object
LengthofServiceOverall. Overall Length of Service at Institute (in years)                                                                                        596 non-null object
LengthofServiceCurrent. Length of Service at current workplace (in years)                                                                                        596 non-null object
dtypes: float64(2), object(70)
memory usage: 395.0+ KB

In [33]:
tafe_survey.isnull().sum()

Record ID                                                                                                                                                          0
Institute                                                                                                                                                          0
WorkArea                                                                                                                                                           0
CESSATION YEAR                                                                                                                                                     7
Reason for ceasing employment                                                                                                                                      1
Contributing Factors. Career Move - Public Sector                                                                                                                265
Contributing Factors. Career Move - Private Sector                                                                                                               265
Contributing Factors. Career Move - Self-employment                                                                                                              265
Contributing Factors. Ill Health                                                                                                                                 265
Contributing Factors. Maternity/Family                                                                                                                           265
Contributing Factors. Dissatisfaction                                                                                                                            265
Contributing Factors. Job Dissatisfaction                                                                                                                        265
Contributing Factors. Interpersonal Conflict                                                                                                                     265
Contributing Factors. Study                                                                                                                                      265
Contributing Factors. Travel                                                                                                                                     265
Contributing Factors. Other                                                                                                                                      265
Contributing Factors. NONE                                                                                                                                       265
Main Factor. Which of these was the main factor for leaving?                                                                                                     589
InstituteViews. Topic:1. I feel the senior leadership had a clear vision and direction                                                                            94
InstituteViews. Topic:2. I was given access to skills training to help me do my job better                                                                        89
InstituteViews. Topic:3. I was given adequate opportunities for personal development                                                                              92
InstituteViews. Topic:4. I was given adequate opportunities for promotion within %Institute]Q25LBL%                                                               94
InstituteViews. Topic:5. I felt the salary for the job was right for the responsibilities I had                                                                   87
InstituteViews. Topic:6. The organisation recognised when staff did good work                                                                                     95
InstituteViews. Topic:7. Management was generally supportive of me                                                                                                88
InstituteViews. Topic:8. Management was generally supportive of my team                                                                                           94
InstituteViews. Topic:9. I was kept informed of the changes in the organisation which would affect me                                                             92
InstituteViews. Topic:10. Staff morale was positive within the Institute                                                                                         100
InstituteViews. Topic:11. If I had a workplace issue it was dealt with quickly                                                                                   101
InstituteViews. Topic:12. If I had a workplace issue it was dealt with efficiently                                                                               105
                                                                                                                                                                ...
WorkUnitViews. Topic:25. My job allowed me to balance the demands of work and family to my satisfaction                                                           91
WorkUnitViews. Topic:26. My supervisor gave me adequate personal recognition and feedback on my performance                                                       96
WorkUnitViews. Topic:27. My working environment was satisfactory e.g. sufficient space, good lighting, suitable seating and working area                          92
WorkUnitViews. Topic:28. I was given the opportunity to mentor and coach others in order for me to pass on my skills and knowledge prior to my cessation date     93
WorkUnitViews. Topic:29. There was adequate communication between staff in my unit                                                                                99
WorkUnitViews. Topic:30. Staff morale was positive within my work unit                                                                                            96
Induction. Did you undertake Workplace Induction?                                                                                                                 83
InductionInfo. Topic:Did you undertake a Corporate Induction?                                                                                                    270
InductionInfo. Topic:Did you undertake a Institute Induction?                                                                                                    219
InductionInfo. Topic: Did you undertake Team Induction?                                                                                                          262
InductionInfo. Face to Face Topic:Did you undertake a Corporate Induction; Category:How it was conducted?                                                        147
InductionInfo. On-line Topic:Did you undertake a Corporate Induction; Category:How it was conducted?                                                             147
InductionInfo. Induction Manual Topic:Did you undertake a Corporate Induction?                                                                                   147
InductionInfo. Face to Face Topic:Did you undertake a Institute Induction?                                                                                       172
InductionInfo. On-line Topic:Did you undertake a Institute Induction?                                                                                            147
InductionInfo. Induction Manual Topic:Did you undertake a Institute Induction?                                                                                   149
InductionInfo. Face to Face Topic: Did you undertake Team Induction; Category?                                                                                   147
InductionInfo. On-line Topic: Did you undertake Team Induction?process you undertook and how it was conducted.]                                                  147
InductionInfo. Induction Manual Topic: Did you undertake Team Induction?                                                                                         147
Workplace. Topic:Did you and your Manager develop a Performance and Professional Development Plan (PPDP)?                                                         94
Workplace. Topic:Does your workplace promote a work culture free from all forms of unlawful discrimination?                                                      108
Workplace. Topic:Does your workplace promote and practice the principles of employment equity?                                                                   115
Workplace. Topic:Does your workplace value the diversity of its employees?                                                                                       116
Workplace. Topic:Would you recommend the Institute as an employer to others?                                                                                     121
Gender. What is your Gender?                                                                                                                                     106
CurrentAge. Current Age                                                                                                                                          106
Employment Type. Employment Type                                                                                                                                 106
Classification. Classification                                                                                                                                   106
LengthofServiceOverall. Overall Length of Service at Institute (in years)                                                                                        106
LengthofServiceCurrent. Length of Service at current workplace (in years)                                                                                        106
Length: 72, dtype: int64

* As some of the columns in both the columns are named different but imply the same, we might need to rename the columns so that there is order while combining the data and answering questions like:
* Are employees who only worked for the institutes for a short period of time resigning due to some kind of dissatisfaction? What about employees who have been there longer?
* Are younger employees resigning due to some kind of dissatisfaction? What about older employees?
* There are some cells in dete_survey which contain 'Not Stated' rather than Nan. While cleaning data we have to check uniformity in the columns, that is the values in the columns should have similar datatype and should basically belong to the same group as the other data. For example, if a column contains the marks of a student, we should make sure that there are no values which represent grades or percentage.
* There are many columns in both the surveys that are not needed for our analysis.
* The number of columns in both the surveys are not same, we will need to filter the useful columns.

In [68]:
columns = {'Record ID': 'id',
'CESSATION YEAR':'cease_date',
'Reason for ceasing employment':'separation_type',
'Gender. What is your Gender?':'gender',
'CurrentAge. Current Age':'age',
'Employment Type. Employment Type':'employment_status',
'Classification. Classification':'position',
'LengthofServiceOverall. Overall Length of Service at Institute (in years)':'institute_service',
'LengthofServiceCurrent. Length of Service at current workplace (in years)':'role_service',
'Contributing Factors. Dissatisfaction':'factors_diss',
'Contributing Factors. Job Dissatisfaction':'factors_job_diss'
        }
tafe_survey = tafe_survey.rename(columns=columns)

In [74]:
# we choose columns to drop on the same basis as we did for dete_survey
tafe_survey = tafe_survey.drop(tafe_survey.columns[17:66], axis = 1)

In [75]:
tafe_survey.head()
tafe_survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 17 columns):
id                                                     702 non-null float64
Institute                                              702 non-null object
WorkArea                                               702 non-null object
cease_date                                             695 non-null float64
separation_type                                        701 non-null object
Contributing Factors. Career Move - Public Sector      437 non-null object
Contributing Factors. Career Move - Private Sector     437 non-null object
Contributing Factors. Career Move - Self-employment    437 non-null object
Contributing Factors. Ill Health                       437 non-null object
Contributing Factors. Maternity/Family                 437 non-null object
factors_diss                                           437 non-null object
factors_job_diss                                       437 non-null object
Contributing Factors. Interpersonal Conflict           437 non-null object
Contributing Factors. Study                            437 non-null object
Contributing Factors. Travel                           437 non-null object
Contributing Factors. Other                            437 non-null object
Contributing Factors. NONE                             437 non-null object
dtypes: float64(2), object(15)
memory usage: 93.3+ KB

In [76]:
tafe_survey.duplicated(['id']).value_counts()

False    702
dtype: int64

In [49]:
tafe_survey['separation_type'].value_counts(dropna=False)

Resignation                 340
Contract Expired            127
Retrenchment/ Redundancy    104
Retirement                   82
Transfer                     25
Termination                  23
NaN                           1
Name: separation_type, dtype: int64

In the DETE-Survey dataset we see that in the column separation_type there are 3 values containing the word 'Resignation'. Whereas, in the TAFE-Survey dataset, there is only one.

In [50]:
tafe_resignation=tafe_survey.copy()[tafe_survey['separation_type'].str.contains(r'Resignation',na=False)]
tafe_resignation.head()

,id,Institute,WorkArea,cease_date,separation_type,Contributing Factors. Career Move - Public Sector,Contributing Factors. Career Move - Private Sector,Contributing Factors. Career Move - Self-employment,Contributing Factors. Ill Health,Contributing Factors. Maternity/Family,factors_diss,factors_job_diss,Contributing Factors. Interpersonal Conflict,Contributing Factors. Study,Contributing Factors. Travel,Contributing Factors. Other,Contributing Factors. NONE
3,6.341399e+17,Mount Isa Institute of TAFE,Non-Delivery (corporate),2010.0,Resignation,-,-,-,-,-,-,-,-,-,Travel,-,-
4,6.341466e+17,Southern Queensland Institute of TAFE,Delivery (teaching),2010.0,Resignation,-,Career Move - Private Sector,-,-,-,-,-,-,-,-,-,-
5,6.341475e+17,Southern Queensland Institute of TAFE,Delivery (teaching),2010.0,Resignation,-,-,-,-,-,-,-,-,-,-,Other,-
6,6.341520e+17,Barrier Reef Institute of TAFE,Non-Delivery (corporate),2010.0,Resignation,-,Career Move - Private Sector,-,-,Maternity/Family,-,-,-,-,-,Other,-
7,6.341537e+17,Southern Queensland Institute of TAFE,Delivery (teaching),2010.0,Resignation,-,-,-,-,-,-,-,-,-,-,Other,-

In [52]:
tafe_resignation['cease_date'].value_counts()

2011.0    116
2012.0     94
2010.0     68
2013.0     55
2009.0      2
Name: cease_date, dtype: int64

In [77]:
#tafe_resignation['institute_service'].value_counts(dropna=False)

In [78]:
def update_vals(x):
    if x =='-':
        return False
    elif pd.isnull(x):
        return np.nan
    else:
        return True
tafe_resignation['dissatisfied']= tafe_resignation[['factors_diss', 'factors_job_diss']].applymap(update_vals).any(1, skipna=False)
tafe_resignation['dissatisfied'].head()
tafe_resignation_up = tafe_resignation.copy()
tafe_resignation_up['dissatisfied'].value_counts(dropna=False)

False    241
True      91
NaN        8
Name: dissatisfied, dtype: int64

In [79]:
dete_resignation_up['institute']='DETE'
tafe_resignation_up['institute']='TAFE'

In [80]:
combined=pd.concat([dete_resignation_up,tafe_resignation_up], ignore_index=True)
combined.shape

C:\Users\bayonetta\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.

(651, 53)

In [81]:
combined_null = combined.isnull().sum()
combined_null

Contributing Factors. Career Move - Private Sector     319
Contributing Factors. Career Move - Public Sector      319
Contributing Factors. Career Move - Self-employment    319
Contributing Factors. Ill Health                       319
Contributing Factors. Interpersonal Conflict           319
Contributing Factors. Maternity/Family                 319
Contributing Factors. NONE                             319
Contributing Factors. Other                            319
Contributing Factors. Study                            319
Contributing Factors. Travel                           319
Institute                                              311
WorkArea                                               311
aboriginal                                             644
age                                                    345
business_unit                                          619
career_move_to_private_sector                          340
career_move_to_public_sector                           340
cease_date                                              16
classification                                         490
dete_start_date                                        368
disability                                             643
dissatisfaction_with_the_department                    340
dissatisfied                                             8
employment_conditions                                  340
employment_status                                      344
factors_diss                                           319
factors_job_diss                                       319
gender                                                 349
id                                                       0
ill_health                                             340
institute                                                0
institute_service                                      378
interpersonal_conflicts                                340
job_dissatisfaction                                    340
lack_of_job_security                                   340
lack_of_recognition                                    340
maternity/family                                       340
nesb                                                   642
none_of_the_above                                      340
physical_work_environment                              340
position                                               343
region                                                 386
relocation                                             340
role_start_date                                        380
separation_type                                          0
separationtype                                         340
south_sea                                              648
study/travel                                           340
torres_strait                                          651
traumatic_incident                                     340
work_life_balance                                      340
work_location                                          340
workload                                               340
dtype: int64

In [82]:
columns_drops = combined_null[combined_null >= 400]

In [83]:
combined=combined.dropna(thresh=200,axis=1)
combined

,Contributing Factors. Career Move - Private Sector,Contributing Factors. Career Move - Public Sector,Contributing Factors. Career Move - Self-employment,Contributing Factors. Ill Health,Contributing Factors. Interpersonal Conflict,Contributing Factors. Maternity/Family,Contributing Factors. NONE,Contributing Factors. Other,Contributing Factors. Study,Contributing Factors. Travel,...,region,relocation,role_start_date,separation_type,separationtype,study/travel,traumatic_incident,work_life_balance,work_location,workload
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Central Queensland,False,2006.0,Resignation-Other reasons,Resignation,False,False,False,False,False
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Central Office,False,1997.0,Resignation-Other reasons,Resignation,False,False,False,False,False
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,North Queensland,False,2009.0,Resignation-Other reasons,Resignation,False,False,False,False,False
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,False,2008.0,Resignation-Other employer,Resignation,False,False,False,False,False
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Far North Queensland,True,2009.0,Resignation-Move overseas/interstate,Resignation,False,False,False,False,False
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Far North Queensland,False,1998.0,Resignation-Other reasons,Resignation,False,False,False,False,False
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Central Queensland,False,2010.0,Resignation-Other employer,Resignation,False,False,False,False,False
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,South East,True,NaN,Resignation-Other reasons,Resignation,False,False,False,False,False
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Central Queensland,False,1982.0,Resignation-Other employer,Resignation,False,False,False,False,False
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Darling Downs South West,False,2009.0,Resignation-Other reasons,Resignation,False,False,False,False,False
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Metropolitan,False,1998.0,Resignation-Other reasons,Resignation,False,False,True,False,False
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,North Queensland,False,2012.0,Resignation-Other reasons,Resignation,False,False,True,True,False
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,South East,False,2002.0,Resignation-Other reasons,Resignation,False,False,True,False,False
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Central Office,False,2011.0,Resignation-Other employer,Resignation,False,False,False,False,False
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,False,2003.0,Resignation-Other reasons,Resignation,False,True,False,False,False
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Central Office,False,2009.0,Resignation-Other reasons,Resignation,False,False,True,False,False
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Central Queensland,False,2011.0,Resignation-Other reasons,Resignation,False,False,False,False,False
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Central Queensland,False,NaN,Resignation-Move overseas/interstate,Resignation,False,False,True,False,False
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,South East,False,1980.0,Resignation-Other employer,Resignation,False,False,False,False,False
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Metropolitan,False,1994.0,Resignation-Other reasons,Resignation,False,False,True,False,False
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,North Coast,False,2011.0,Resignation-Move overseas/interstate,Resignation,False,False,False,False,False
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,North Coast,False,1976.0,Resignation-Other reasons,Resignation,False,False,True,False,True
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,South East,True,2010.0,Resignation-Move overseas/interstate,Resignation,False,False,False,False,False
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,South East,True,2010.0,Resignation-Move overseas/interstate,Resignation,False,False,False,False,False
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,South East,False,1993.0,Resignation-Other reasons,Resignation,False,False,False,False,False
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Metropolitan,False,2008.0,Resignation-Other employer,Resignation,False,False,False,False,False
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Darling Downs South West,False,2012.0,Resignation-Other employer,Resignation,False,False,False,False,False
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Central Queensland,True,2011.0,Resignation-Other reasons,Resignation,False,False,False,False,False
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Central Office,False,NaN,Resignation-Other reasons,Resignation,False,False,False,True,False
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Far North Queensland,True,2011.0,Resignation-Other reasons,Resignation,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,Career Move - Private Sector,-,-,-,-,-,-,-,Study,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
622,-,-,-,-,-,-,-,Other,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
623,Career Move - Private Sector,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
624,-,-,-,Ill Health,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
625,-,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
626,-,-,-,-,-,-,-,Other,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
627,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
628,-,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
629,-,-,-,-,Interpersonal Conflict,-,-,Other,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
630,-,Career Move - Public Sector,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
631,-,-,-,-,-,-,-,Other,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
632,Career Move - Private Sector,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
633,-,-,-,Ill Health,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
634,-,-,-,-,-,-,-,Other,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
635,-,Career Move - Public Sector,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
636,-,-,-,-,-,-,-,Other,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
637,-,Career Move - Public Sector,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
638,-,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
639,-,Career Move - Public Sector,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
640,-,-,-,-,-,-,NONE,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
641,-,-,-,Ill Health,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
642,-,-,-,Ill Health,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
643,-,-,-,Ill Health,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
644,Career Move - Private Sector,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
645,Career Move - Private Sector,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
646,Career Move - Private Sector,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
647,-,Career Move - Public Sector,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
648,-,Career Move - Public Sector,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
649,-,-,-,-,-,-,-,Other,-,-,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN
650,-,-,Career Move - Self-employment,-,-,-,-,-,-,Travel,...,NaN,NaN,NaN,Resignation,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
combined['institute_service']

0       7.0
1      18.0
2       3.0
3      15.0
4       3.0
5      14.0
6       5.0
7       NaN
8      30.0
9      32.0
10     15.0
11     39.0
12     17.0
13      7.0
14      9.0
15      6.0
16      1.0
17      NaN
18     35.0
19     38.0
20      1.0
21     36.0
22      3.0
23      3.0
24     19.0
25      4.0
26      9.0
27      1.0
28      6.0
29      1.0
       ...
621     NaN
622     NaN
623     NaN
624     NaN
625     NaN
626     NaN
627     NaN
628     NaN
629     NaN
630     NaN
631     NaN
632     NaN
633     NaN
634     NaN
635     NaN
636     NaN
637     NaN
638     NaN
639     NaN
640     NaN
641     NaN
642     NaN
643     NaN
644     NaN
645     NaN
646     NaN
647     NaN
648     NaN
649     NaN
650     NaN
Name: institute_service, Length: 651, dtype: float64

In [85]:
type(combined['institute_service'][2])

numpy.float64

In [86]:
def service_category(val):
    if pd.isna(val):
        return np.nan
    elif val < 3:
        return 'New'
    elif val < 7:
        return 'Experienced'
    elif val < 11:
        return 'Established'
    else:
        return 'Veteran'

In [87]:
combined['institute_service'].value_counts(dropna=False)

NaN      378
 5.0      23
 1.0      22
 3.0      20
 0.0      20
 6.0      17
 4.0      16
 9.0      14
 2.0      14
 7.0      13
 13.0      8
 8.0       8
 20.0      7
 15.0      7
 12.0      6
 22.0      6
 17.0      6
 10.0      6
 14.0      6
 16.0      5
 18.0      5
 24.0      4
 23.0      4
 11.0      4
 39.0      3
 32.0      3
 19.0      3
 21.0      3
 36.0      2
 30.0      2
 25.0      2
 28.0      2
 26.0      2
 29.0      1
 42.0      1
 38.0      1
 27.0      1
 41.0      1
 35.0      1
 49.0      1
 34.0      1
 33.0      1
 31.0      1
Name: institute_service, dtype: int64